version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .

    container_name: alexandr-e-backend

    ports:
      - "8080:8080"

    depends_on:
      - db

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-dev}

      LOGO_DEV_KEY: ${LOGO_DEV_KEY}

      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}

volumes:
  db-data:
