app:
    jwt-secret: bXlzZWNyZXRrZXlteXNlY3JldGtleW15c2VjcmV0a2V5IQ==
    jwt-expiration-ms: 36000000 # 10 heures
    jwt-refresh-secret: bXlyZWZyZXNoc2VjcmV0a2V5bXlyZWZyZXNoc2VjcmV0a2V5IQ==
    jwt-refresh-expiration-ms: 604800000 # 7 jours
    frontend-url: http://localhost:5173, http://192.168.1.49:5173/
    opengraph:
      allowed-domains:
        wikipedia.org,
        github.com,
        stackoverflow.com
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: validate   # Flyway
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  config:
    import: optional:application-secrets.yml