CREATE SEQUENCE IF NOT EXISTS user_id_seq START
WITH
    1 INCREMENT BY 1;

CREATE TABLE app_user (
    id BIGSERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL
);